name: Code tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest httpx
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Download model
        uses: wei/wget@v1.1.1
        with:
          args: https://www.dropbox.com/s/iga6rfyqpq0lnra/20_cat_classes_model.h5 --no-check-certificate -P ./models/
      - name: Run flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run tests
        run: |
          pytest ./app_tests.py